### ISSUE TITLE
Switching robot from backloading to frontloading

### ISSUE THREAD

**Issue by bid-p** [pchintalapudi/itz#1]
It sets the initial position to facing the mogo once, and then ceases to do that no matter whether I switch the bot to back/front. A program restart is required to make that happen again.

**Comment by pchintalapudi** [comment]
If you're going to write an issue, you need to give a step-by-step process to replicate the issue. I can't spend 30 minutes just trying to figure out how you created a bug, only to wonder if it's not a bug and you're just misinterpreting how the robot stuff works.

**Comment by pchintalapudi** [comment]
That said if you believe it's a real issue put a step-by-step process here.

**Comment by bid-p** [comment]
I apologize. First, create a robot that has a "frontloading" intake, making sure that the default one "backloading" was selected. You will notice that once you create and load a robot that has a "frontloading" intake", the robot flips its' initial position to face the first mobile goal, as one usually does in autonomous. However, after, for example, running a timer, playing through a mode such as skills, and using "CTRL-R" to reset the field, the frontloading robot goes back to facing the wrong direction (backloading). Nothing short of a program restart is able to get the robot to flip back into position again.

**Comment by pchintalapudi** [comment]
Bug fixed
