### ISSUE TITLE
not sure what that robot selection thing is

### ISSUE THREAD

**Issue by bid-p** [pchintalapudi/itz#15]
![image](https://user-images.githubusercontent.com/22570121/37629410-d9406606-2b9b-11e8-9c1a-0dca7059741c.png)

**Comment by bid-p** [comment]
update: is that supposed to select the robot for which the score report shows?

**Comment by bid-p** [comment]
lowkey have no idea

**Comment by pchintalapudi** [comment]
Yeah it's a work in progress.

**Comment by pchintalapudi** [comment]
Still in progress, but this issue is no longer relevant.
