### ISSUE TITLE
Not really issue, but driving into cones and mobile goals looks super stuttery.

### ISSUE THREAD

**Issue by bid-p** [pchintalapudi/itz#5]
Not really issue, but driving into cones and mobile goals looks super stuttery. (More than versions previous to 3.5.)

**Comment by pchintalapudi** [comment]
Issue update: Stutteriness now only occurs when driving into > 5 other objects, and when cascading collisions occur. A cascading collision occurs when one object collides with another object (object 2), and then object 2 subsequently collides with another object (object 3).

**Comment by bid-p** [comment]
looks good now.
